name: Go Builder

permissions:
      contents: write
      checks: write
      actions: read
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read

on:
  release:
    types: [released]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build GO Binary
      run: |
           cd go
           go mod tidy
           CGO_ENABLED=0 go build -v -o duckserver server.go

    - name: Build GO Magic
      run: |
           cd go
           go mod tidy
           go build -v -o duckserver_magic server_magic.go
           
    - name: Patch glibc for backwards compatibility
      uses: lmangani/polyfill-glibc-action@1.1.4
      continue-on-error: true
      id: polyfill
      with:
        glibc: "2.28"
        target: "/github/workspace/go/duckserver"
        
    - name: Patch glibc for backwards compatibility
      uses: lmangani/polyfill-glibc-action@1.1.4
      continue-on-error: true
      with:
        glibc: "2.27"
        target: "/github/workspace/go/duckserver_magic"
        
    - name: Upload Release Binary
      uses: alexellis/upload-assets@0.4.0
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
          asset_paths: '["./go/duckserver", "./go/duckserver_magic"]'
