name: Go Builder

permissions:
      contents: write
      checks: write
      actions: read
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read

on:
  release:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build GO Binary
      run: |
           cd go
           go mod tidy
           go build -v -o duckserver main.go

    - name: Upload Release Binary
      uses: alexellis/upload-assets@0.4.0
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
          asset_paths: '["./go/duckserver]'
